name: hyll_test
description: Hyll Test
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  animations: ^2.0.7
  app_settings: ^5.0.0
  auto_route: ^7.7.1
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  device_info_plus: ^9.0.2
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.19.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  http: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  modal_bottom_sheet: ^3.0.0-pre
  pin_code_fields: ^8.0.1
  responsive_framework: ^1.1.0
  rxdart: ^0.27.7
  sentry_flutter: ^7.8.0
  simple_animations: ^4.2.0

dev_dependencies:
  auto_route_generator: ^7.2.0
  bloc_test: ^9.1.3
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  integration_test:
    sdk: flutter
  intl_utils: ^2.8.3
  json_serializable: ^6.7.1
  mocktail: ^0.3.0

dependency_overrides:
  dio: 5.3.0 # https://github.com/Milad-Akarie/auto_route_library/issues/1005

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80

  integrations:
    flutter_svg: true

  assets:
    exclude:
      - assets/env/*
      - config/
    outputs:
      class_name: AppAssets

flutter:
  uses-material-design: true
  
  assets:
   - assets/images/
